# Generated by Django 4.1.2 on 2022-10-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименнование товара",
                        max_length=50,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        help_text="Введите цену товара", verbose_name="Цена товараа"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales_receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sum",
                    models.FloatField(
                        help_text="Введите общую сумму чека",
                        verbose_name="Общая сумма чека",
                    ),
                ),
                (
                    "sale_time",
                    models.DateField(
                        blank=True,
                        help_text="Введите время формирования чека",
                        null=True,
                        verbose_name="Время создания чека",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store_as_st",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименнование магазина",
                        max_length=50,
                        verbose_name="Название магазина",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес магазина",
                        max_length=200,
                        verbose_name="Адрес магазина",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        help_text=" Выберите товар",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystorereportapp.item",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "sales_receipt_i",
                    models.ForeignKey(
                        help_text=" Выберите чек",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystorereportapp.sales_receipt",
                        verbose_name="Чек",
                    ),
                ),
                (
                    "store_id",
                    models.ForeignKey(
                        help_text=" Выберите магазин",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mystorereportapp.store_as_st",
                        verbose_name="Магазин",
                    ),
                ),
            ],
        ),
    ]
